name: Deploy Astro Blog to Contabo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Debug env
        run: |
          node -v
          npm -v
          ls -la
          cat package.json || true

      # npm ci échoue s'il n'y a pas de package-lock.json → fallback sur npm install
      - name: Install dependencies (ci or install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Si "build" n'existe pas, tente npx astro build
      - name: Build site (npm run build or npx astro build)
        run: |
          if npm run | grep -q "^  build"; then
            npm run build
          else
            npx astro build
          fi

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 62.84.191.34 >> ~/.ssh/known_hosts

      - name: Deploy dist/ via rsync
        run: |
          rsync -avz --delete dist/ root@62.84.191.34:/var/www/mad2moi/blog/
