name: Deploy Astro Blog to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4) Build Astro
      - name: Build Astro site
        run: npm run build

      # 5) Déployer uniquement /dist via rsync
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete
          path: dist/
          remote_path: /var/www/mad2moi/blog/
          remote_host: 62.84.191.34
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
